# Configuration documentation: https://docs.helix-editor.com/master/configuration.html

# Set theme
theme = "nord_transparent"

[editor]
scrolloff = 5
mouse = true
middle-click-paste = false
scroll-lines = 3
line-number = "relative"
cursorline = true
cursorcolumn = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 400
completion-trigger-len = 2
auto-info = true
true-color = true
rulers = [120]
bufferline = "never"
color-modes = false
auto-pairs = true
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right  = ["diagnostics", "selections", "position", "file-encoding"]
separator = "|"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.lsp]
display-messages = false
auto-signature-help = true
display-signature-help-docs = true

[editor.cursor-shape]
normal = "bar"
insert = "block"
select = "underline"

[editor.file-picker]
hidden = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.search]
smart-case = true
wrap-around = true

[editor.indent-guides]
character = "╎" # Box Drawings Light Double Dash Vertical Symbol (U+254E)
render = true
