# Colors (Nord)

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'

[cursor.style]
blinking = "On"
shape = "Block"

[cursor]
unfocused_hollow = true

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "BoldItalics"

[font.italic]
family = "FiraCode Nerd Font"
style = "MediumItalics"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
opacity = 0.85

[general]
live_config_reload = true
