name: Update Windows Hosts File

on:
  schedule:
    - cron: '30 5 * * *' # Runs every day at 12:30 AM EST (5:30 AM UTC)
  workflow_dispatch: # Allows manual triggering of the workflow from the Actions tab

permissions:
  contents: write

jobs:
  update-hosts-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create directory
      run: mkdir -p windows/System32/drivers/etc
      
    - name: Download hosts file
      run: |
        wget -O windows/System32/drivers/etc/hosts \
        https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/hosts/native.winoffice.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add windows/System32/drivers/etc/hosts
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Update Windows hosts file'
          git push
        else
          echo "No changes to commit"
        fi
