name: Update README Tree

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-readme-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up tree and env
        run: |
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Generate README tree section
        run: bash .github/scripts/update-readme-tree.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update repository structure tree in README"
          branch: main
